_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 1 #196 -> r=5,6 -> because of dataset size r=5,6 * 10,335/233 = 0,248
  BASE_LR: 0.0214 #0.12
  STEPS: (17280, 23040)
  MAX_ITER: 100000 #116000
  WARMUP_ITERS: 0 #3625
TEST:
  EVAL_PERIOD: 7200 #29000
VIS_PERIOD: 1 #2320
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val')
  TEST: ('SUNRGBD_test',) 
  CATEGORY_NAMES: ('chair', 'table', 'cabinet', 'car', 'lamp', 'books', 'sofa', 'pedestrian', 'picture', 'window', 'pillow', 'truck', 'door', 'blinds', 'sink', 'shelves', 'television', 'shoes', 'cup', 'bottle', 'bookcase', 'laptop', 'desk', 'cereal box', 'floor mat', 'traffic cone', 'mirror', 'barrier', 'counter', 'camera', 'bicycle', 'toilet', 'bus', 'bed', 'refrigerator', 'trailer', 'box', 'oven', 'clothes', 'van', 'towel', 'motorcycle', 'night stand', 'stove', 'machine', 'stationery', 'bathtub', 'cyclist', 'curtain', 'bin')
MODEL:
  ROI_HEADS:
    NAME: 'ROIHeads_Boxer' # name of the class that is the 3d predictor
    NUM_CLASSES: 50
  ROI_CUBE_HEAD:
    NUMBER_OF_PROPOSALS: 1000
  META_ARCHITECTURE: 'BoxNet' # name of the overall arch that calls the ROI_HEADS.NAME and ROI_CUBE_HEAD.NAME